version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: educagame_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: educagame
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ../EducaGame-back
    container_name: educagame_backend
    restart: always
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/educagame
    ports:
      - "4000:3000"
    depends_on:
      - postgres

  frontend:
    build: ../educagame-front
    container_name: educagame_frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://educagame_backend:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: